### ISSUE TITLE
OpenSimplex noise instead of Perlin?

### ISSUE THREAD

**Issue by Tr4sHCr4fT** [whichonespink44/Realistic-Terrain-Generation#135]
like evaluated on reddit:
https://www.reddit.com/r/Minecraft/comments/2ikiaw/opensimplex_noise_for_terrain_generation_instead/
and proposed in the original thread of rwg,

simplex noise should generate terrain more naturally

any plans to implement it?

**Comment by whichonespink44** [comment]
Apparently, it was already implemented on RWG before I forked it:

https://github.com/Ted80-Minecraft-Mods/Realistic-World-Gen/commit/a1cce770858695ad73ff50bb9fe9d169ad16d103

**Comment by Tr4sHCr4fT** [comment]
ah, great! got confused because the function is still called perlin... he just replaced the algorithm

**Comment by Ezoteric** [comment]
Yeah, ktspence rewrote the perlin file for ted :)
