### ISSUE TITLE
Rivers are huge and don't look like rivers

### ISSUE THREAD

**Issue by whichonespink44** [whichonespink44/Realistic-Terrain-Generation#137]
Similar to #136

**Comment by Ezoteric** [comment]
Rivers are huge? You mean the big lakes? Cause a lake is called in the biome it is that can either be river or a biome

**Comment by whichonespink44** [comment]
Yeah, I think this has gotten a lot better since we replaced the rtg_ rivers with the vanilla ones in 0725317. Do you think we're alright to close this one then?

**Comment by Ezoteric** [comment]
Well tbh I didn't understand what you meant in the first place haha RWG itself has no big river so.... I think you can yes
