### ISSUE TITLE
Frequency option for cobblestone boulders

### ISSUE THREAD

**Issue by whichonespink44** [whichonespink44/Realistic-Terrain-Generation#141]
Being able to enable/disable cobblestone boulders is nice, but it would be even better if you could set a frequency.

**Comment by whichonespink44** [comment]
This should be easy to implement as a 1/x config option... so whenever there is an opportunity for a cobblestone boulder to generate, there would be a 1 in X chance that it would actually generate. Setting it to 2, for example, would make them spawn half as frequently... a setting of 1 would make them generate as often as they could... and anything less than 1 would prevent them from generating at all.

**Comment by Ezoteric** [comment]
Yeah should be easy but its blocked code :( 
I cant find the part where it says after X blocks get the next one. 

Its again blocked with P codes :(

**Comment by whichonespink44** [comment]
I was thinking of something a little simpler (though probably a bit hacky)... basically, wherever there's an instance of **if ( ConfigRTG.enableCobblestoneBoulders ) {**, we do the following:

* Check to see if cobblestone boulders is enabled
* If it is, then generate a random number between 1 and the frequency setting
* If the random number is 1, then run the rest of the code... if it's anything else, then don't.

If it works, we could do the same for emerald generation, and maybe even other areas of generation, like the trees that have fallen over... or cactuses! (that would be a good one to have... always thought it was a bit weird to see cacti in forests :)

**Comment by Ezoteric** [comment]
about the cactus, isnt it possble to set a min temp for it to be able to let it spawn  ? :P that would fix it also right :)

**Comment by whichonespink44** [comment]
Good idea about the cactus... I'll create a separate issue for that one. :+1:
