### ISSUE TITLE
RTG generates BOP biomes that have been disabled in the BOP config

### ISSUE THREAD

**Issue by whichonespink44** [whichonespink44/Realistic-Terrain-Generation#143]
Might need to add a config option to enable/disable BOP biomes.

**Comment by Ezoteric** [comment]
Maybe its also time to get a config dir for RWG, i think we gonna end up like BOP anyway with all the configs we want to add in the future :P

**Comment by Ezoteric** [comment]
Hey as vanilla is currently added via support can't I just use the same way you added the config option to disable vanilla biomes for bop ? If so I can do that for you

**Comment by whichonespink44** [comment]
Sorry for the late reply... yep, we should be able to do that for all the support biomes. I'm not sure how to add a config directory, but I think it's worth doing. I'll add it to the issue tracker so I don't forget.

**Comment by Ezoteric** [comment]
OK ill get on it, ill just check how bop creates the dir and ill manage if not you hear from me ;)

**Comment by whichonespink44** [comment]
I've just assigned this to you... I've also removed myself from most of the other issues (I was just doing it because I thought it needed one). I've only added myself to the issues I'm. So if there's anything else you want to work on, just let me know and I'll assign it to you so we both know who's doing what. And feel free to unassign yourself if you want, or assign stuff to me, or whatever... just trying to leverage what GitHub has to offer to make our lives a little easier :) If ends up being too much hassle, we can just play it by ear.

**Comment by Ezoteric** [comment]
Lolz I still don't know how github works but I'll found that out sooner or later haha

BTW as ik rendering maps from your latest source I think I start to understand what you mean by large rivers and that problem is still here. They are huge and have small islands on them (not the good islands) I'll post screenies later haha

**Comment by Ezoteric** [comment]
http://i.imgur.com/uNB7zvN.png

that whole region is a river :O

**Comment by Ezoteric** [comment]
Made the config its just not creating it :P

**Comment by whichonespink44** [comment]
I think I'm getting the hang of branches, so... I think if you commit this stuff to your branch, I can switch to your branch, fix it (hopefully), and then push it back to master via pull request.

**Comment by Ezoteric** [comment]
If config is fixed this should also work if im correct

**Comment by whichonespink44** [comment]
Cool, I've not tested this, but it looked fine. I'll close this for now, but re-open if it's still not working.

**Comment by Ezoteric** [comment]
Sweet I'll check asap
