### ISSUE TITLE
Create an RTG config directory to store all the RTG configs.

### ISSUE THREAD

**Issue by whichonespink44** [whichonespink44/Realistic-Terrain-Generation#150]

**Comment by Ezoteric** [comment]
Got this, working somehow but the files remain empty but it did create the files i made :P

Ill upload it in my branch so you can have a look.

I also made the bop config.

**Comment by Ezoteric** [comment]
I updated my branch with the configs you can have a look why its not writing the stuff into the config file :P

**Comment by whichonespink44** [comment]
Ok, if you update your branch from master and then delete your config files, this should be working now. :) Re-open if not.

**Comment by Ezoteric** [comment]
Ok I'll. Check in a while I'm generating a huge map haha
