### ISSUE TITLE
ChunkGeneratorRealistic.java need fix

### ISSUE THREAD

**Issue by Ezoteric** [whichonespink44/Realistic-Terrain-Generation#151]
Line 790 orso ->>>  worldObj.setBlock(sn1 + x, sn3, sn2 + y, Blocks.snow_layer, 0, 2);

I turned off this line and it doesnt spawn those snow layers in warm biomes and on trees but also no snow on snow biomes, there was no snow anywhere. So if you can tell it to ask if the biome is cold enough to place it then it wont spawn in warm biomes and on trees anymore :) i think :palm_tree: ;)

If easy, try add it to 0.0.6 plz if taking to long then its sad :P

**Comment by Ezoteric** [comment]
get to work lazy ass ;) haha

**Comment by whichonespink44** [comment]
Haha, nice one -only just got back from dinner. Real life is over now... time to mod some Minecraft!! :)

**Comment by whichonespink44** [comment]
Oh, and feel free to close this issue if you've fixed it - if not, let me know and I'll look into it.

**Comment by Ezoteric** [comment]
Euh... this was a question for you :P 

i dont know how to do that haha

**Comment by Ezoteric** [comment]
![mappp](https://cloud.githubusercontent.com/assets/14137626/9977803/28c87ab2-5f14-11e5-8edf-2ef5d24ec149.png)

**Comment by whichonespink44** [comment]
Interesting... looks like turning it off in the config just stops the vanilla River biome from generating as a biome, but it's still using them as transitional biomes? Hmmm. I wonder what would happen if you disabled oceans as well. Probably the same thing.

**Comment by Ezoteric** [comment]
dunno but when rivers was on there was hardly any ocean in many maps so i tested it :P

ill check what happens when i turn off oceans :P

**Comment by Ezoteric** [comment]
If oceans are off they wont create btw.

Ill keep rivers off for my testing and prolly wont ever set it on when playing when ever we get to that point :P

**Comment by whichonespink44** [comment]
Ok, I'm looking at this now. Do you still want me to do what you asked in the original post above? If so, I'll start looking into it.

**Comment by Ezoteric** [comment]
Yes, I have no idea how to add it. So if you can make sure it only generates in snow biomes I think the ugly snow patches are gone from trees and warmer biomes

**Comment by Ezoteric** [comment]
It may interfere with biome bleeding but we'll see

**Comment by whichonespink44** [comment]
Ok, I've added a possible fix in 350703a.

I've tested in Cold Beaches, and there was snow. And I've tested in Beaches, and there was no snow. But I haven't tested in a normal world yet, so the rivers might still cause problems. I'll do some more testing in about an hour.

**Comment by Ezoteric** [comment]
I just finished generating a map, and yes this is the fix BUT as i expected the biome bleeding also stopped, but this is prolly also cause the biomes it bleeds into is never cold but always hot or wet.

So when you have fixed the biomes transitions i think you need to change the temp to max cold so it still bleeds into cold but not in temp hot or warm (if your making them by snow cold temp hot wet) :P

**Comment by Ezoteric** [comment]
Check it out, i also used big trees mod as on all those big trees where snow layers as well (was also a complaint of some ppl)

![snowfix1](https://cloud.githubusercontent.com/assets/14137626/9980908/889d158c-5fab-11e5-80ce-ba60fab2f24e.jpg)
