### ISSUE TITLE
Got a crash with just RTG and Journeymap installed

### ISSUE THREAD

**Issue by whichonespink44** [whichonespink44/Realistic-Terrain-Generation#153]
Crash report: https://gist.github.com/whichonespink44/5352183d6a1d41d0f6cf

MCF thread: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2524489-wip-realistic-terrain-generation-0-0-5?comment=44

**Comment by Ezoteric** [comment]
I know, its the cause of too much falling blocks.
I had this error 1 time in 100 times i made maps till now.

I think its that extreme hills gravel stuff its just too much to handle for worldgen

**Comment by Ezoteric** [comment]
In both extreme hills surface files:	
if(beach)
            			{
	            			blocks[(y * 16 + x) * 256 + k] = beachBlock;
	            			gravel = false; //This will fix falling blocks spam crash (this was true)

**Comment by whichonespink44** [comment]
Ok, I'll take a look at extreme hills now.

**Comment by Ezoteric** [comment]
If you gonna look into it ill reopen it for you as you might forget ;)

**Comment by whichonespink44** [comment]
Yep, looking into this now.

**Comment by whichonespink44** [comment]
This proving to be very difficult to debug because it's just not crashing for me. Maybe some of the changes we made since 0.0.5 have fixed the crash?

Maybe we should release 0.0.6 and ask people to see if it's still happening for them. I'll add some extra error logging to the Chunk Generator so I can figure out where exactly it's crashing.

**Comment by Ezoteric** [comment]
No i had this since we started, i havent got this error since 0.0.4

**Comment by whichonespink44** [comment]
I'm pretty sure this is fixed. I'll close this for now and re-open if it crops up again.
