### ISSUE TITLE
Before you release 0.0.6

### ISSUE THREAD

**Issue by Ezoteric** [whichonespink44/Realistic-Terrain-Generation#158]
Im generating a huge map now (takes a bout 30 min) to see if everything thus far works like intended.

changes:
config folders
bop config + biomes settings
snow layer fix
few biomes pimped

I am checking if the above is working.

**Comment by Ezoteric** [comment]
feel free to add things to add to test, after that render ill test TC4

**Comment by Ezoteric** [comment]
OK, here you see how ugly it became without the snow bleeding, but then again its all the fault of snow biomes getting warm neighbors :(

Anyway the rest pretty much speaks for it self, i fixed the ocean ice layers also

Testing TC compat now

Some eyecandy:
This map is almost 100 000 chunks big :P
![150map1](https://cloud.githubusercontent.com/assets/14137626/9981613/45c5d4da-5fc2-11e5-99ec-e26476d47457.jpg)

**Comment by Dream-Master** [comment]
looks very nice !
Only the snow boarders look a bit sharp.

**Comment by Ezoteric** [comment]
Yeah i know until we fixed the snow to cold transition it's either this or the snow in deserts take your pick 😉

**Comment by Ezoteric** [comment]
Btw updated my branch

**Comment by whichonespink44** [comment]
Sorry, real world stuff took over.. now back on the scene. I'll take a look at your branch and get get back to resolving this crash issue.

**Comment by Ezoteric** [comment]
No worries man haha 

I tried using RTG in my mod pack and I think it's big trees mod that fucking me over but I had only 7 fps lolz

**Comment by whichonespink44** [comment]
I made a tweak to the river biome before I released 0.0.6 which should have improved the sharpness of the snow biomes. I'll do some more testing today after work to make sure.

**Comment by Ezoteric** [comment]
Sure I'll check also :)
